title: Zachary Horton: Portfolio
logo: /assets/img/logo.png
description: My portfolio containing recent projects and also prior university work.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
