title: Zachary Horton's Portfolio
logo: /assets/img/mylogo.png
description: Portfolio for recent projects and prior university work.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
