title: Zachary Horton's Portfolio
logo: /assets/img/mylogo.png
description: Portfolio for recent projects and prior university work.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
- jekyll-remote-theme # add this line to the plugins list if you already have one
site_favicon: favicon.ico
permalink: /:categories/:year/:month/:day/:title:output_ext